package CalculatorModule;


/**
* CalculatorModule/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorModule.idl
* Sunday, May 28, 2023 11:47:04 AM IST
*/

public interface CalculatorOperations 
{
  double add (double num1, double d2);
  double sub (double num1, double d2);
} // interface CalculatorOperations
