package StringModule;


/**
* StringModule/OpearationsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringModule.idl
* Sunday, May 28, 2023 5:42:52 PM IST
*/

public abstract class OpearationsPOA extends org.omg.PortableServer.Servant
 implements StringModule.OpearationsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("concat", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // StringModule/Opearations/concat
       {
         String s1 = in.read_string ();
         String s2 = in.read_string ();
         String $result = null;
         $result = this.concat (s1, s2);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:StringModule/Opearations:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Opearations _this() 
  {
    return OpearationsHelper.narrow(
    super._this_object());
  }

  public Opearations _this(org.omg.CORBA.ORB orb) 
  {
    return OpearationsHelper.narrow(
    super._this_object(orb));
  }


} // class OpearationsPOA
