package StringModule;


/**
* StringModule/OpearationsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringModule.idl
* Sunday, May 28, 2023 5:42:52 PM IST
*/

public interface OpearationsOperations 
{
  String concat (String s1, String s2);
} // interface OpearationsOperations
