package StringModule;

/**
* StringModule/OpearationsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringModule.idl
* Sunday, May 28, 2023 5:42:52 PM IST
*/

public final class OpearationsHolder implements org.omg.CORBA.portable.Streamable
{
  public StringModule.Opearations value = null;

  public OpearationsHolder ()
  {
  }

  public OpearationsHolder (StringModule.Opearations initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StringModule.OpearationsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StringModule.OpearationsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StringModule.OpearationsHelper.type ();
  }

}
