package StringModule;


/**
* StringModule/Opearations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringModule.idl
* Sunday, May 28, 2023 5:42:52 PM IST
*/

public interface Opearations extends OpearationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Opearations
