package StringModule;


/**
* StringModule/Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringModule.idl
* Sunday, May 28, 2023 6:22:49 PM IST
*/

public interface Operations extends OperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Operations
