package StringModule;


/**
* StringModule/OperationsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringModule.idl
* Sunday, May 28, 2023 6:22:49 PM IST
*/

public interface OperationsOperations 
{
  String concat (String s1, String s2);
} // interface OperationsOperations
